### ISSUE TITLE
Similar name Repo

### ISSUE THREAD

**Issue by fulin426** [IssueHunt/readme#1]
Hi, 

I was practicing React and learning how to use the GitHub API when I created a project with a similar name. My project was mainly for practice. Your project is leaps and bounds from my idea though!

https://github.com/fulin426/Issues-Hunt

**Comment by kazup01** [comment]
Hi @fulin426 , thank you for your comment. Your idea "Issues Hunt" is nice!
If you have any feedback about "IssueHunt", let me know. 😄We are more powerful together!
